### ISSUE TITLE
a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by Shringa13** [EmilianoGagliardiEmanueleGhelfi/CNN-compression-performance#2]
Hello,
While Testing I am getting this error:

Traceback (most recent call last):
  File "workflow.py", line 294, in <module>
    main(model_instance, strtobool(args.train[0]), strtobool(args.quantize[0]), strtobool(args.evaluate[0]))
  File "workflow.py", line 252, in main
    o_current_dict = perf_stderr2dict(o_perf_std_err)
  File "workflow.py", line 186, in perf_stderr2dict
    perf_output_list = perf_output.split("\n")
TypeError: a bytes-like object is required, not 'str'

**Comment by EmanueleGhelfi** [comment]
Hi, 
it seems you are testing the performance of the model. Have you installed perf tool (https://perf.wiki.kernel.org/index.php/Main_Page)?

**Comment by EmanueleGhelfi** [comment]
Closing due to inactivity
